package funding

// Seeds is the hand-curated, hand-scored list (scored once, 2026-09-03).
// Score = suitability NOW for a Vienna solo founder, no entity, no revenue, with
// the "Palantir for land use" pitch plus a free African protected-area app.
// Deadlines: ISO when confirmed; otherwise DeadlineNote carries the cycle + "verify".
// Re-seed via /admin/funding → "reseed" (keeps status & user notes).
var Seeds = []Entry{
	// ---------- Austria: pre-company cash ----------
	{Key: "wa-gruendungsstipendium", Name: "Wirtschaftsagentur Wien – Gründungsstipendium", URL: "https://wirtschaftsagentur.at/aktuelle-foerderungen-der-wirtschaftsagentur-wien/foe-gruendungsstipendium/",
		Kind: "grant", Track: "at", Amount: "€8,000 per founder (max 3), 6 months + coaching", Deadline: "2026-09-15", DeadlineNote: "window 15 Jul–15 Sep 2026; programme ends 31 Dec 2026",
		Eligibility: "Natural person, Vienna residence, no current self-employment, ≤20h employed, no AMS founder programme.", Note: "Closest deadline. Small, but it is exactly the pre-founding phase. Info session was 1 Sep; apply online.",
		Score: 90, Why: "Perfect stage fit, Vienna, no entity needed, 12 days left."},
	{Key: "aws-preseed-innovative", Name: "aws Preseed – Innovative Solutions", URL: "https://www.aws.at/en/aws-preseed-innovative-solutions/",
		Kind: "grant", Track: "at", Amount: "up to €89k grant (€100k w/ gender bonus), 80–90% rate", DeadlineNote: "rolling",
		Eligibility: "Natural persons intending to found, or company ≤6 months old. Impact & scalability; ≥10% own cash.", Note: "Pitch the land-governance platform as impact-led govtech. Pair with Gründungsstipendium.",
		Score: 85, Why: "Main Austrian pre-seed grant for exactly this stage."},
	{Key: "aws-preseed-deeptech", Name: "aws Preseed – Deep Tech", URL: "https://www.aws.at/en/aws-preseed-deep-tech/",
		Kind: "grant", Track: "at", Amount: "up to €267k grant (€300k w/ gender bonus), 80–90% rate", DeadlineNote: "rolling",
		Eligibility: "Natural persons or micro-enterprise ≤6 months; exceptional scientific/technical innovation; ≥10% own cash.", Note: "Only if the LIDAR watershed segmentation / data fusion can be framed as defensible deep tech. aws decides the track.",
		Score: 70, Why: "3× the money; needs a tech co-founder & IP story."},
	{Key: "aws-first-incubator", Name: "aws First Incubator", URL: "https://www.aws.at/en/aws-first-incubator/",
		Kind: "accelerator", Track: "at", Amount: "up to €49k grant (90%); €55k/100% w/ gender bonus", DeadlineNote: "2026 call closed 23 Jun; 2027 call ~spring (verify)",
		Eligibility: "Individuals/teams with a first-company idea; mandatory Vienna startup camp.", Note: "Pre-company format with cash. Watch for 2027.",
		Score: 75, Why: "Great fit, but closed until 2027."},
	{Key: "netidee", Name: "netidee – Internet Stiftung (open-source project grants)", URL: "https://www.netidee.at/einreichen/projekt",
		Kind: "grant", Track: "at", Amount: "up to €60k per project (pool €300k/yr)", DeadlineNote: "2026 call closed 7 Jul; next call ~Mar–Jul 2027 (verify)",
		Eligibility: "Natural persons, associations, startups – anyone in Austria; result must be open source.", Note: "Fits the public kohlschwarz.at apps (groundwater, parcels, tallest trees) rather than the commercial platform.",
		Score: 70, Why: "Open-source apps are already there; €60k, no entity needed."},
	{Key: "wa-innovation", Name: "Wirtschaftsagentur Wien – Förderung Innovation", URL: "https://wirtschaftsagentur.at/aktuelle-foerderungen-der-wirtschaftsagentur-wien/foerderung-innovation/",
		Kind: "grant", Track: "at", Amount: "up to €300k, 45% (small firms)", Deadline: "2026-12-31", DeadlineNote: "cut-offs 31 Aug & 31 Dec 2026",
		Eligibility: "Vienna SME or founder; value creation in Vienna; own financing for 55%.", Note: "After GmbH + co-financing. Personnel & dev costs eligible.",
		Score: 60, Why: "Solid follow-on once incorporated."},
	{Key: "wa-lebensqualitaet", Name: "Wirtschaftsagentur Wien – Lebensqualität Wien", URL: "https://wirtschaftsagentur.at/aktuelle-foerderungen-der-wirtschaftsagentur-wien/",
		Kind: "grant", Track: "at", Amount: "up to €150k", Deadline: "2026-12-31", DeadlineNote: "window 1 Mar–31 Dec 2026",
		Eligibility: "Vienna SMEs/founders; social/sustainability products realised in Vienna.", Note: "Only if piloted with Vienna green-space / climate-adaptation authorities (MA 22, MA 42, MA 45).",
		Score: 45, Why: "Needs a Vienna-city pilot angle."},
	{Key: "ffg-impact-innovation", Name: "FFG Impact Innovation", URL: "https://www.ffg.at/en/programme/impactinnovation",
		Kind: "grant", Track: "at", Amount: "up to €75k at 50%; social track €105k at 70%", DeadlineNote: "2026 call closed 12 Mar; next call ~early 2027 (verify)",
		Eligibility: "Individuals, startups, associations; topic-open; participatory innovation process with users.", Note: "Co-design with a Land or park authority = textbook Impact Innovation project.",
		Score: 65, Why: "Method fit; individuals eligible; wait for 2027."},
	{Key: "ffg-kleinprojekt", Name: "FFG Basisprogramm – Kleinprojekt", URL: "https://www.ffg.at/en/programme/small-scale",
		Kind: "grant", Track: "at", Amount: "costs up to €150k; grant 45% (60% w/ research partner)", Deadline: "2026-12-31", DeadlineNote: "rolling within 2026 programme",
		Eligibility: "Austrian SME/startup with legal entity; R&D character.", Note: "Add TU Wien/BOKU as partner for 60%.",
		Score: 50, Why: "Needs GmbH and co-financing."},
	{Key: "ffg-basisprogramm", Name: "FFG Basisprogramm (General Programme 2026)", URL: "https://www.ffg.at/en/call/general-programme-2026",
		Kind: "loan", Track: "at", Amount: "costs up to €3m; startups up to 70% (grant share ≤31%, rest loan)", Deadline: "2026-12-31", DeadlineNote: "rolling",
		Eligibility: "Austrian companies incl. in formation; TRL 5–8; no consortium needed.", Note: "Later; needs balance sheet for the loan component.",
		Score: 40, Why: "Too heavy for a solo pre-company."},
	{Key: "ffg-asap", Name: "FFG ASAP – Austrian Space Applications Programme", URL: "https://www.ffg.at/en/program/austrian-space-applications-programme-0",
		Kind: "grant", Track: "space", Amount: "2025 budget €12.85m; project max ~€2.1m; feasibility studies smaller", DeadlineNote: "next call not announced (2025 closed 10 Apr); typically annual (verify)",
		Eligibility: "Austrian companies & research bodies; instruments from feasibility to cooperative R&D.", Note: "2025 topics included satellite monitoring of soil sealing – i.e. exactly this. Team up with TU Wien GEO / ZAMG-GeoSphere.",
		Score: 70, Why: "Best thematic fit in Austria; needs entity + partner."},
	{Key: "greenstart", Name: "Klima- und Energiefonds – greenstart", URL: "https://greenstart.at/",
		Kind: "accelerator", Track: "at", Amount: "€10k each Top-10; +€20k each Top-3", DeadlineNote: "no 2026 call yet; last deadline 14 Feb 2025 (verify)",
		Eligibility: "Persons intending to found, startups ≤3 yrs, Austria; climate/energy relevance.", Note: "Climate-adaptation (flood/fire/drought preparedness) angle.",
		Score: 65, Why: "Pre-company friendly, if a call reopens."},
	{Key: "climatelaunchpad-at", Name: "ClimateLaunchpad Austria (EIT Climate-KIC)", URL: "https://climatelaunchpad.org/countries/austria/",
		Kind: "accelerator", Track: "at", Amount: "free bootcamp + national/global finals (cash prizes vary)", DeadlineNote: "2026 closed 30 Mar; 2027 intake ~Feb/Mar (verify)",
		Eligibility: "No entity required; <2 yrs, <€200k funding, no sales.", Note: "Good forcing function for the pitch; leads into EIT ClimAccelerator.",
		Score: 65, Why: "Stage fit; 2027."},
	{Key: "inits", Name: "INiTS Vienna – SCALEup / STARTKapital", URL: "https://www.inits.at/en/scaleup/",
		Kind: "accelerator", Track: "at", Amount: "12-month incubation; optional €100k STARTKapital equity", DeadlineNote: "rolling intro meeting; cohort cut-offs (verify)",
		Eligibility: "Early-stage tech startups in Vienna; selection board.", Note: "Ask directly about solo-founder acceptance; also a place to find a technical co-founder.",
		Score: 70, Why: "Best local incubator; co-founder pool."},
	{Key: "accent", Name: "accent incubator Lower Austria (also hosts ESA BIC)", URL: "https://accent.at/",
		Kind: "accelerator", Track: "at", Amount: "incubation, coaching, investor access", Deadline: "2026-09-29", DeadlineNote: "next selection date; initial interview first (verify)",
		Eligibility: "High-tech founders willing to base the company in Lower Austria.", Note: "Only relevant if you'd seat the GmbH in NÖ (e.g. Tulln/Wr. Neustadt) – then also unlocks ESA BIC €50k.",
		Score: 50, Why: "Location trade-off."},
	{Key: "esa-bic-austria", Name: "ESA BIC Austria (Science Park Graz / accent)", URL: "https://www.sciencepark.at/esa-bic-austria/",
		Kind: "accelerator", Track: "space", Amount: "€50k zero-equity incentive + up to 24 months incubation", DeadlineNote: "permanent call; cut-offs announced per round (verify)",
		Eligibility: "Natural persons or companies ≤5 yrs with a clear space (EO) link; must locate in Styria, Lower Austria, Upper Austria or Carinthia.", Note: "Copernicus/VIIRS/LIDAR fusion is a textbook ESA BIC case. Founders can incorporate upon acceptance.",
		Score: 70, Why: "Space-data fit is excellent; relocation needed."},

	// ---------- EU / space ----------
	{Key: "cassini-accelerator", Name: "CASSINI Business Accelerator – Batch 8", URL: "https://www.cassini.eu/accelerator/",
		Kind: "accelerator", Track: "space", Amount: "€75k non-dilutive voucher + 6 months coaching", Deadline: "2026-10-02", DeadlineNote: "batch 8 closes 2 Oct 2026",
		Eligibility: "EU-registered startup using EU space data (Copernicus/Galileo); legal entity required.", Note: "Would need a GmbH before 2 Oct – tight but doable. Otherwise batch 9 in ~6 months.",
		Score: 60, Why: "Exact fit; entity required in 4 weeks."},
	{Key: "esa-incubed", Name: "ESA Φ-lab InCubed", URL: "https://incubed.esa.int/how-to-apply/",
		Kind: "grant", Track: "space", Amount: "co-funding 50% (up to 80% for SMEs), no fixed cap", DeadlineNote: "rolling",
		Eligibility: "Industry-led company in ESA member state; needs MVP path & matching funds.", Note: "For commercial EO analytics later.",
		Score: 50, Why: "Later stage; needs entity & matching money."},
	{Key: "esa-osip", Name: "ESA OSIP – Open Discovery Ideas", URL: "https://technology.esa.int/page/funding-your-ideas",
		Kind: "grant", Track: "space", Amount: "studies €20–100k; early tech €50–175k; co-funded research ≤€90k", DeadlineNote: "rolling open channels; campaigns dated",
		Eligibility: "Anyone submits; contracting needs a legal entity.", Note: "Only for a genuinely novel EO method (e.g. LIDAR-watershed parcel objects × Sentinel time series).",
		Score: 45, Why: "Novelty bar high."},
	{Key: "eic-accelerator", Name: "EIC Accelerator", URL: "https://eic.ec.europa.eu/eic-funding-opportunities/eic-accelerator_en",
		Kind: "equity", Track: "eu", Amount: "grant ≤€2.5m + equity €0.5–10m", Deadline: "2026-11-04", DeadlineNote: "full-application cut-off 4 Nov 2026; 2027 dates TBA",
		Eligibility: "EU SME or natural person committing to incorporate; TRL 6–9; breakthrough innovation.", Note: "Long shot; revisit after pilots and a team.",
		Score: 30, Why: "Too early; keep on horizon."},
	{Key: "horizon-cl6-biodiv", Name: "Horizon Europe Cluster 6 – BIODIV 2026 topics", URL: "https://rea.ec.europa.eu/funding-and-grants/horizon-europe-cluster-6-food-bioeconomy-natural-resources-agriculture-and-environment/biodiversity-and-ecosystem-services_en",
		Kind: "grant", Track: "eu", Amount: "€76m across 7 topics", Deadline: "2026-09-17", DeadlineNote: "17 Sep 2026",
		Eligibility: "Consortia of ≥3 entities from 3 countries.", Note: "Only by joining an existing consortium as SME partner – ask BOKU / Umweltbundesamt / EODC who is submitting.",
		Score: 25, Why: "Consortium-only; two weeks."},
	{Key: "digital-europe-genai-pa", Name: "Digital Europe – GenAI for Public Administrations", URL: "https://digital-strategy.ec.europa.eu/en/funding/digital-europe-programme-calls-proposals",
		Kind: "grant", Track: "eu", Amount: "topic budget ~€21m", DeadlineNote: "2026 closed 3 Mar; next 2027 call TBA (verify)",
		Eligibility: "Consortium with public administrations.", Note: "Thematically on point (govtech AI on public data); needs a Land/ministry as partner.",
		Score: 30, Why: "Consortium; later."},
	{Key: "eit-climaccelerator", Name: "EIT Climate-KIC ClimAccelerator", URL: "https://climaccelerator.climate-kic.org/",
		Kind: "accelerator", Track: "eu", Amount: "stage grants typically €5–50k + programme", DeadlineNote: "regional programmes; various dates (verify)",
		Eligibility: "Climate startups in Europe; early stage accepted.", Note: "Entry via ClimateLaunchpad or a regional ClimAccelerator (Austria via Impact Hub?).",
		Score: 55, Why: "Stage-appropriate climate route."},

	// ---------- Conservation tech & nature grants (Five Megapixel / CAR) ----------
	{Key: "wildlabs-awards", Name: "WILDLABS Awards", URL: "https://wildlabs.net/en/fellowships-awards-programme",
		Kind: "grant", Track: "conservation", Amount: "$10k or $50k", DeadlineNote: "annual; ~Mar 2027 (verify)",
		Eligibility: "Conservation-tech projects globally; $50k tier needs a team of 2+ and an organisational bank account; Arm hardware angle.", Note: "Five Megapixel Conservation (fire→movement interpolation, live asset feed) is squarely conservation tech.",
		Score: 80, Why: "Strongest conservation-tech fit."},
	{Key: "gfw-small-grants", Name: "Global Forest Watch Small Grants Fund (WRI)", URL: "https://www.globalforestwatch.org/grants-and-fellowships/apply/",
		Kind: "grant", Track: "conservation", Amount: "typically up to $40k", DeadlineNote: "annual; ~Feb 2027 (verify)",
		Eligibility: "Civil-society orgs using GFW data; registered nonprofit (partner with CAR NGO / park).", Note: "App already ingests GFW/Hansen alerts. Apply via a CAR partner (your former NGO?).",
		Score: 70, Why: "Direct data-user fit; needs NGO vehicle."},
	{Key: "biopama-ac", Name: "BIOPAMA Action Component (IUCN/JRC, EU)", URL: "https://action.biopama.org/",
		Kind: "grant", Track: "africa", Amount: "historically up to €400k", DeadlineNote: "next round TBA (verify)",
		Eligibility: "PA agencies, NGOs, legal entities in ACP countries; CAR eligible.", Note: "PA-management-effectiveness tooling is its core purpose. Consortium with CAR Ministry/parks.",
		Score: 65, Why: "Big, CAR-eligible, PA-focused."},
	{Key: "rob-walton-foundation", Name: "Rob Walton Foundation (direct approach)", URL: "https://www.robwaltonfoundation.org/",
		Kind: "grant", Track: "conservation", Amount: "invitation-only; large", DeadlineNote: "no open call – relationship-based",
		Eligibility: "Invited conservation partners.", Note: "You are already in contact re CAR parks; frame Five Megapixel as national reporting infrastructure they can fund into a partner (e.g. African Parks / WCS).",
		Score: 60, Why: "Warm contact; no formal route."},
	{Key: "global-conservation", Name: "Global Conservation – Global Park Defense", URL: "https://globalconservation.org/projects-home",
		Kind: "program", Track: "conservation", Amount: "project-specific", DeadlineNote: "rolling",
		Eligibility: "Endangered national parks in developing countries with committed authorities.", Note: "Position the app as the monitoring layer for a Park Defense partnership in CAR.",
		Score: 50, Why: "Partnership, not cash for you."},
	{Key: "prince-bernhard", Name: "Prince Bernhard Nature Fund", URL: "https://www.pbnf.nl/",
		Kind: "grant", Track: "conservation", Amount: "small (€5–20k typical)", DeadlineNote: "next call TBA (verify)",
		Eligibility: "Small, locally-led conservation initiatives.", Note: "Via CAR park partner.",
		Score: 40, Why: "Small; local partner needed."},
	{Key: "rufford", Name: "Rufford Small Grants", URL: "https://apply.ruffordsmallgrants.org/",
		Kind: "grant", Track: "conservation", Amount: "£7–18k", DeadlineNote: "rolling",
		Eligibility: "Early-career conservationists in developing countries; funds via organisation.", Note: "For a CAR field team validating alerts on the ground.",
		Score: 40, Why: "Small; team in CAR."},
	{Key: "clp-award", Name: "Conservation Leadership Programme – Team Award", URL: "https://www.conservationleadershipprogramme.org/awards-opportunities/team-awards/",
		Kind: "grant", Track: "conservation", Amount: "up to $15k", DeadlineNote: "annual; ~Jan 2027 (verify)",
		Eligibility: "Teams of 3+ early-career conservationists in eligible countries.", Note: "CAR team could apply with the app as tool.",
		Score: 35, Why: "Not you; a CAR team."},
	{Key: "natgeo-grants", Name: "National Geographic Society – Explorer grants", URL: "https://www.nationalgeographic.org/explore/grants-investments",
		Kind: "grant", Track: "conservation", Amount: "typically $20–100k", Deadline: "2026-09-23", DeadlineNote: "current RFP (Okavango) 23 Sep 2026; other RFPs open periodically",
		Eligibility: "Individuals; RFP-specific themes.", Note: "Watch for a technology / Africa RFP; the exe.dev blog story is NatGeo-shaped.",
		Score: 50, Why: "Individual-eligible; wait for a matching RFP."},
	{Key: "gbif-ebbe-nielsen", Name: "GBIF Ebbe Nielsen Challenge", URL: "https://www.gbif.org/ebbe",
		Kind: "prize", Track: "prize", Amount: "€20k pool", DeadlineNote: "annual; announced early 2027 (verify)",
		Eligibility: "Individuals/teams; open innovation on GBIF data.", Note: "Add GBIF occurrences to the parcel/park apps → cheap prize shot.",
		Score: 50, Why: "Low effort, individual-eligible."},
	{Key: "iucn-sos-ias", Name: "IUCN SOS – EU Invasive Alien Species Rapid Response", URL: "https://www.iucnsos.org/call-for-proposals/",
		Kind: "grant", Track: "conservation", Amount: "€10–50k", Deadline: "2027-02-10", DeadlineNote: "10 Feb 2027",
		Eligibility: "Organisations in the EU; IAS early detection.", Note: "Only if the Austrian parcel/object classification is pointed at invasive species detection.",
		Score: 30, Why: "Niche pivot."},
	{Key: "climate-change-ai", Name: "Climate Change AI – Innovation Grants", URL: "https://www.climatechange.ai/grants",
		Kind: "grant", Track: "conservation", Amount: "up to $150k", DeadlineNote: "next call TBA (verify)",
		Eligibility: "Academic PI usually required.", Note: "Partner with TU Wien / BOKU on land-use / fire / drought decision support.",
		Score: 45, Why: "Needs academic PI."},

	// ---------- Big prizes (long shots) ----------
	{Key: "mit-solve", Name: "MIT Solve – Global Challenges 2026/27", URL: "https://solve.mit.edu/challenges",
		Kind: "prize", Track: "prize", Amount: "$10k+ per Solver; sponsor prizes up to $100k+", DeadlineNote: "challenges launch Sep 2026; deadline TBA (verify)",
		Eligibility: "Early-stage tech solutions worldwide; no incorporation required.", Note: "Very good fit for an early prototype with public data + AI + environmental outcome.",
		Score: 75, Why: "Open to pre-company; strong narrative fit."},
	{Key: "keeling-curve", Name: "Keeling Curve Prize", URL: "https://www.climatecurve.org/kcp",
		Kind: "prize", Track: "prize", Amount: "$50k", DeadlineNote: "opens 1 Nov 2026; closes ~Jan 2027 (verify)",
		Eligibility: "Active projects with quantified GHG reduction.", Note: "Needs a deforestation-avoided number from CAR.",
		Score: 35, Why: "Requires quantified impact."},
	{Key: "zayed", Name: "Zayed Sustainability Prize (Climate Action)", URL: "https://zayedsustainabilityprize.com/",
		Kind: "prize", Track: "prize", Amount: "$1m per category", DeadlineNote: "2027 cycle closed Jun 2026; next ~Jun 2027 (verify)",
		Eligibility: "Registered SME/nonprofit with proven results.", Note: "After a government deployment.",
		Score: 35, Why: "Needs traction."},
	{Key: "earthshot", Name: "The Earthshot Prize (Protect & Restore Nature)", URL: "https://earthshotprize.org/",
		Kind: "prize", Track: "prize", Amount: "£1m", DeadlineNote: "nomination-only; nominators submit ~Q1 each year (verify)",
		Eligibility: "Nomination via official nominators (WRI, Conservation X Labs, NatGeo…).", Note: "Cultivate a nominator; long shot.",
		Score: 30, Why: "Nomination-only."},
	{Key: "elevate-prize", Name: "Elevate Prize", URL: "https://elevateprize.org/",
		Kind: "prize", Track: "prize", Amount: "$300k unrestricted", DeadlineNote: "2027 cycle TBA",
		Eligibility: "Established social-impact leaders with measurable impact.", Note: "Founder story fits; needs an operating organisation.",
		Score: 30, Why: "Later."},
	{Key: "falling-walls-venture", Name: "Falling Walls Venture", URL: "https://falling-walls.com/venture",
		Kind: "prize", Track: "prize", Amount: "visibility, investor access", DeadlineNote: "~Apr 2027 (verify)",
		Eligibility: "Science-based startups nominated by institutions/investors.", Note: "Via TU Wien / INiTS nomination.",
		Score: 40, Why: "Needs nominator."},
	{Key: "social-impact-award", Name: "Social Impact Award Austria", URL: "https://austria.socialimpactaward.net/",
		Kind: "prize", Track: "prize", Amount: "€ small prizes + incubation", DeadlineNote: "annual; ~May (verify)",
		Eligibility: "Students / young founders ≤30 mostly.", Note: "Likely age-limited – check.",
		Score: 20, Why: "Probably ineligible."},

	// ---------- Africa-side vehicles ----------
	{Key: "digital-africa-fuze", Name: "Digital Africa – Fuzé", URL: "https://digital-africa.co/",
		Kind: "equity", Track: "africa", Amount: "€20–100k", DeadlineNote: "rolling",
		Eligibility: "Pre-seed startups incorporated/operating in Africa.", Note: "If Five Megapixel becomes a CAR/Africa-incorporated venture.",
		Score: 45, Why: "Needs African entity."},
	{Key: "developpp-ventures", Name: "develoPPP Ventures (GIZ/DEG)", URL: "https://www.developpp.de/en/application/ventures",
		Kind: "grant", Track: "africa", Amount: "up to €100k matching", Deadline: "2026-11-15", DeadlineNote: "15 Nov 2026",
		Eligibility: "Startup registered in eligible African country; PoC, first revenue, matching capital.", Note: "Later; CAR not always in target list.",
		Score: 35, Why: "Not yet eligible."},
	{Key: "ada-business-partnerships", Name: "ADA Wirtschaftspartnerschaften", URL: "https://www.entwicklung.at/en/funding-portal/private-sector-and-development/business-partnerships",
		Kind: "grant", Track: "africa", Amount: "inception €30k; partnership up to €300k (50%)", DeadlineNote: "intake paused; may resume autumn 2026 (verify)",
		Eligibility: "Austrian/EEA company with balance sheet & own cash; local partner.", Note: "Natural Austrian route for the CAR component once the GmbH exists. Inception phase (€30k) is the entry door.",
		Score: 40, Why: "Right door, wrong timing."},
	{Key: "global-innovation-fund", Name: "Global Innovation Fund", URL: "https://www.globalinnovation.fund/apply-for-funding",
		Kind: "grant", Track: "africa", Amount: "$50k–15m", DeadlineNote: "closed; next window TBA",
		Eligibility: "Evidence-driven innovations in lower-income countries.", Note: "After CAR pilot evidence.",
		Score: 30, Why: "Later."},

	// ---------- Corporate programs (credits/data; need entity or NGO partner) ----------
	{Key: "gee-noncommercial", Name: "Google Earth Engine – Noncommercial partner tier", URL: "https://developers.google.com/earth-engine/guides/noncommercial_tiers",
		Kind: "program", Track: "program", Amount: "free compute quota", DeadlineNote: "rolling",
		Eligibility: "Nonprofits/research/government; not commercial startups.", Note: "For the free conservation app via NGO/park authority.",
		Score: 65, Why: "Immediate, free, fits Five Megapixel."},
	{Key: "planet-tfo", Name: "Planet – Tropical Forest Observatory / NGO access", URL: "https://www.planet.com/get-started/",
		Kind: "program", Track: "program", Amount: "donated/discounted high-res imagery", DeadlineNote: "rolling",
		Eligibility: "Nonprofits & researchers monitoring tropical forests.", Note: "Gold-mine riverbed detection in CAR needs this. (Planet Startup Program is closed.)",
		Score: 60, Why: "Data you can't get otherwise."},
	{Key: "aws-activate", Name: "AWS Activate", URL: "https://aws.amazon.com/startups/credits/",
		Kind: "program", Track: "program", Amount: "$1k–200k credits", DeadlineNote: "rolling",
		Eligibility: "Incorporated startup; larger tiers via accelerator affiliation.", Note: "Day 1 after GmbH.",
		Score: 55, Why: "Easy post-incorporation."},
	{Key: "nvidia-inception", Name: "NVIDIA Inception", URL: "https://www.nvidia.com/en-us/startups/",
		Kind: "program", Track: "program", Amount: "credits, training, investor intros", DeadlineNote: "rolling",
		Eligibility: "Incorporated, <10 yrs, website, ≥1 developer.", Note: "Post-incorporation.",
		Score: 50, Why: "Easy; moderate value."},
	{Key: "esri-startup", Name: "Esri Startup Program", URL: "https://www.esri.com/en-us/about/partners/our-partners/startups",
		Kind: "program", Track: "program", Amount: "free ArcGIS + go-to-market", DeadlineNote: "rolling",
		Eligibility: "Incorporated software company <5 yrs, <$2m revenue.", Note: "Governments buy Esri; being in their partner list helps sales more than the licenses.",
		Score: 50, Why: "Channel to government buyers."},
	{Key: "google-startups-accel-eu", Name: "Google for Startups Accelerator: Europe (AI)", URL: "https://startup.google.com/programs/accelerator/europe-israel/",
		Kind: "accelerator", Track: "program", Amount: "equity-free; cloud credits", DeadlineNote: "2027 cycle TBA",
		Eligibility: "Incorporated AI startups with team/traction.", Note: "Alpha Earth is Google's – interesting partner or competitor conversation.",
		Score: 35, Why: "Too early."},

	// ---------- Investors (after GmbH + technical co-founder) ----------
	{Key: "superorganism", Name: "Superorganism (biodiversity VC)", URL: "https://www.superorganism.com/", Kind: "vc", Track: "vc", Amount: "pre-seed/seed, undisclosed", DeadlineNote: "rolling",
		Eligibility: "Biodiversity-tech startups; global.", Note: "Most on-thesis specialist: biodiversity, remote sensing, geospatial infra.", Score: 65, Why: "Thesis match #1."},
	{Key: "satgana", Name: "Satgana", URL: "https://www.satgana.com/about", Kind: "vc", Track: "vc", Amount: "€100–500k", DeadlineNote: "rolling",
		Eligibility: "Pre-seed climate, Europe & Africa.", Note: "Only fund covering both Vienna and Bangui.", Score: 60, Why: "Europe+Africa, small ticket."},
	{Key: "public-io", Name: "PUBLIC (govtech)", URL: "https://www.public.io/", Kind: "vc", Track: "vc", Amount: "undisclosed", DeadlineNote: "rolling",
		Eligibility: "European govtech.", Note: "Understands public procurement; 'Palantir for land use' lands here.", Score: 60, Why: "Govtech specialist."},
	{Key: "planet-a", Name: "Planet A Ventures", URL: "https://planet-a.com/", Kind: "vc", Track: "vc", Amount: "€0.5–4m", DeadlineNote: "rolling",
		Eligibility: "European climate tech, pre-seed–A; science-based impact.", Note: "Land-use & nature intelligence explicitly in scope.", Score: 55, Why: "Good thesis; wants team."},
	{Key: "pale-blue-dot", Name: "Pale blue dot", URL: "https://paleblue.vc/", Kind: "vc", Track: "vc", Amount: "€0.5–2m", DeadlineNote: "rolling",
		Eligibility: "Pre-seed/seed climate software.", Note: "Adaptation/wildfire/drought intelligence.", Score: 55, Why: "Adaptation software fit."},
	{Key: "ponderosa", Name: "Ponderosa Ventures", URL: "https://ponderosavc.com/", Kind: "vc", Track: "vc", Amount: "$100–750k", DeadlineNote: "rolling",
		Eligibility: "Pre-seed/seed climate; land, forestry, resilience.", Note: "Small tickets, land focus.", Score: 55, Why: "Land/forestry thesis."},
	{Key: "nucleus-capital", Name: "Nucleus Capital", URL: "https://www.nucleus-capital.com/", Kind: "vc", Track: "vc", Amount: "pre-seed", DeadlineNote: "rolling",
		Eligibility: "European planetary-health deep tech.", Note: "Wants technical founding team.", Score: 45, Why: "Deep-tech bar."},
	{Key: "speedinvest", Name: "Speedinvest (Vienna)", URL: "https://www.speedinvest.com/", Kind: "vc", Track: "vc", Amount: "€0.5–3m", DeadlineNote: "rolling",
		Eligibility: "European pre-seed/seed; venture-scale.", Note: "Local; climate & deep-tech teams. Warm intro via Consti?", Score: 45, Why: "Local but generalist."},
	{Key: "aws-gruendungsfonds", Name: "aws Gründungsfonds II", URL: "https://www.gruendungsfonds.at/", Kind: "vc", Track: "vc", Amount: "€0.5–5m", DeadlineNote: "rolling",
		Eligibility: "Austrian tech startups with entity, team, traction.", Note: "Later.", Score: 40, Why: "Needs traction."},
	{Key: "aaia", Name: "aaia – Austrian Angel Investors Association", URL: "https://aaia.at/", Kind: "vc", Track: "vc", Amount: "angels €50–500k", DeadlineNote: "rolling / pitch events",
		Eligibility: "Investable Austrian startup.", Note: "Network; pitch events after GmbH.", Score: 45, Why: "Network first."},
	{Key: "seraphim-space", Name: "Seraphim Space (Accelerator + fund)", URL: "https://accelerator.seraphim.vc/", Kind: "vc", Track: "space", Amount: "accelerator + investment", DeadlineNote: "cohorts ~Feb & Sep (verify)",
		Eligibility: "Incorporated spacetech, TRL 5+.", Note: "EO analytics is their core.", Score: 50, Why: "EO specialist; later."},
	{Key: "2150", Name: "2150", URL: "https://www.2150.vc/", Kind: "vc", Track: "vc", Amount: "seed–growth", DeadlineNote: "rolling",
		Eligibility: "Urban/infrastructure tech.", Note: "Infrastructure-risk (roads, bridges, mudslides) angle.", Score: 40, Why: "Infra-risk angle."},
	{Key: "contrarian-ventures", Name: "Contrarian Ventures", URL: "https://www.cventures.vc/", Kind: "vc", Track: "vc", Amount: "€1–4m", DeadlineNote: "rolling",
		Eligibility: "Pre-seed/seed climate, Europe.", Note: "", Score: 40, Why: "Generalist climate."},
	{Key: "uebermorgen", Name: "Übermorgen Ventures", URL: "https://www.uebermorgen.vc/", Kind: "vc", Track: "vc", Amount: "early stage", DeadlineNote: "rolling",
		Eligibility: "European climate.", Note: "DACH.", Score: 40, Why: "DACH climate."},
	{Key: "norrsken-evolve", Name: "Norrsken Evolve / Accelerator", URL: "https://norrskenevolve.vc/", Kind: "vc", Track: "vc", Amount: "pre-seed; accelerator €250k", DeadlineNote: "rolling; accelerator cohort TBA",
		Eligibility: "European impact founders.", Note: "", Score: 45, Why: "Impact pre-seed."},
	{Key: "world-fund", Name: "World Fund", URL: "https://www.worldfund.vc/", Kind: "vc", Track: "vc", Amount: "€1–15m", DeadlineNote: "rolling",
		Eligibility: "Climate deep tech with CPP.", Note: "Too big for now.", Score: 30, Why: "Too late-stage."},
	{Key: "extantia", Name: "Extantia Capital", URL: "https://extantia.com/", Kind: "vc", Track: "vc", Amount: "seed+", DeadlineNote: "rolling",
		Eligibility: "Climate mitigation.", Note: "", Score: 30, Why: "Mitigation focus."},
	{Key: "govtech-fund", Name: "The GovTech Fund (US)", URL: "https://www.govtechfund.com/", Kind: "vc", Track: "vc", Amount: "early stage", DeadlineNote: "rolling",
		Eligibility: "Govtech, mostly US.", Note: "", Score: 30, Why: "US geography."},

	// ---------- Flagship accelerators & co-founder matching ----------
	{Key: "yc", Name: "Y Combinator – Winter 2027 (re-apply)", URL: "https://www.ycombinator.com/apply",
		Kind: "accelerator", Track: "accel", Amount: "$500k ($125k for 7% + $375k uncapped MFN SAFE)", Deadline: "2026-11-02", DeadlineNote: "W27 on-time deadline 2 Nov 2026 8pm PT; decisions 11 Dec; 4 batches/yr",
		Eligibility: "Anyone; company formed after acceptance is fine; solo founders accepted every batch; re-applying is explicitly encouraged.", Note: "Applied F26, not selected. The application's weak spots are fixable before Nov: (1) 'Are people using your product? No' → get one CAR park + one Austrian Land/Bezirk using something weekly; (2) technical co-founder; (3) revenue path: one paid pilot or LOI. Use the update feature after submitting.",
		Score: 55, Why: "1% odds, but $500k and the gaps are exactly the ones to fix anyway."},
	{Key: "antler", Name: "Antler (Berlin / Amsterdam) – co-founder matching residency", URL: "https://www.antler.co/location/germany",
		Kind: "accelerator", Track: "accel", Amount: "pre-seed ~€100k-ish for ~10% after residency (terms per location, verify)", DeadlineNote: "rolling; cohorts ~2×/yr per city (verify)",
		Eligibility: "Individuals pre-team/pre-idea; in-person residency; EU work rights fine.", Note: "Directly solves the co-founder problem. Cost: ~10 weeks in Berlin.",
		Score: 65, Why: "Best structured route to a technical co-founder."},
	{Key: "ef", Name: "Entrepreneur First (London / Paris)", URL: "https://www.joinef.com/",
		Kind: "accelerator", Track: "accel", Amount: "living stipend + ~£/€ pre-seed investment after forming a team (verify)", DeadlineNote: "rolling cohorts (verify)",
		Eligibility: "Individuals, no idea/team/entity needed; in person.", Note: "Same purpose as Antler; more deep-tech flavoured.",
		Score: 55, Why: "Co-founder matching; location cost."},
	{Key: "carbon13", Name: "Carbon13 Venture Builder (Cambridge / Berlin)", URL: "https://carbonthirteen.com/venture-builder/",
		Kind: "accelerator", Track: "accel", Amount: "up to £120k pre-seed for ventures that form", DeadlineNote: "cohorts ~2×/yr (verify)",
		Eligibility: "Individuals without team/entity; venture must target material emissions reduction.", Note: "Climate-only co-founder matching. Frame: avoided deforestation / land-use emissions monitoring.",
		Score: 60, Why: "Climate co-founder matching + cash."},
	{Key: "cdl-climate", Name: "Creative Destruction Lab – Climate stream", URL: "https://creativedestructionlab.com/streams/climate/",
		Kind: "accelerator", Track: "accel", Amount: "no cash; no fee; no equity; objectives-based mentoring", DeadlineNote: "annual applications ~spring–summer (verify)",
		Eligibility: "Science/tech ventures; usually incorporated.", Note: "", Score: 40, Why: "Later; no cash."},
	{Key: "techstars", Name: "Techstars (Europe – climate/space/cities programmes)", URL: "https://www.techstars.com/accelerators",
		Kind: "accelerator", Track: "accel", Amount: "$220k standard", DeadlineNote: "programme-specific, ~4–6 months before cohort",
		Eligibility: "Incorporated at investment.", Note: "Check for a sustainability/space cohort in 2027.", Score: 40, Why: "Generic; needs team."},
	{Key: "seedcamp", Name: "Seedcamp", URL: "https://seedcamp.com/apply/", Kind: "vc", Track: "vc", Amount: "€350k–1m", DeadlineNote: "rolling",
		Eligibility: "European pre-seed; team + product.", Note: "", Score: 40, Why: "After co-founder & MVP."},
	{Key: "kima", Name: "Kima Ventures", URL: "https://www.kimaventures.com/", Kind: "vc", Track: "vc", Amount: "~€150k, fast", DeadlineNote: "rolling",
		Eligibility: "Incorporated; strong team.", Note: "", Score: 35, Why: "Later."},

	// ---------- Civil protection / disaster-risk (the actual €600m/yr buyer) ----------
	{Key: "ffg-kiras", Name: "FFG KIRAS – Austrian security research", URL: "https://www.ffg.at/kiras",
		Kind: "grant", Track: "at", Amount: "cooperative R&D projects, typically €0.5–2m per consortium", DeadlineNote: "annual call ~autumn/winter (verify 2026 Leitfaden)",
		Eligibility: "Austrian legal entities in consortium; a public Bedarfsträger (BMI, Land, fire/civil-protection authority) must be on board.", Note: "KIRAS is where Austrian disaster-preparedness tooling gets funded. Recruit a Land Katastrophenschutz or the BMI as Bedarfsträger + a research partner (AIT/GeoSphere).",
		Score: 60, Why: "Right buyer, right topic; needs GmbH + consortium."},
	{Key: "ioeb", Name: "IÖB Innovationsplattform – pitch to Austrian public buyers", URL: "https://www.ioeb-innovationsplattform.at/",
		Kind: "procurement", Track: "at", Amount: "challenge-specific contracts; innovation-friendly procurement", DeadlineNote: "rolling; challenges posted continuously",
		Eligibility: "Any supplier; create profile, answer matched challenges; ability to contract at award.", Note: "Skips grants entirely: this is how a ministry/Land can buy a pilot from you legally. Also list your solution in the IÖB marketplace.",
		Score: 70, Why: "Fastest path to a paying government pilot."},
	{Key: "eu-mission-adaptation", Name: "Horizon Europe – EU Mission Adaptation to Climate Change 2026", URL: "https://research-and-innovation.ec.europa.eu/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe/eu-missions-horizon-europe/adaptation-climate-change_en",
		Kind: "grant", Track: "eu", Amount: "€1.6–20m per project", Deadline: "2026-09-23", DeadlineNote: "23 Sep 2026",
		Eligibility: "Consortia with regions/local authorities (Mission Charter signatories).", Note: "Too late for 2026 alone; ask Land NÖ/Steiermark (Charter signatories) who is bidding and join as SME.",
		Score: 30, Why: "Consortium; 3 weeks."},
	{Key: "horizon-cl3-drs", Name: "Horizon Europe Cluster 3 – Disaster-Resilient Society 2026", URL: "https://research-and-innovation.ec.europa.eu/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe/cluster-3-civil-security-society_en",
		Kind: "grant", Track: "eu", Amount: "several €m per project; 70–100%", Deadline: "2026-11-05", DeadlineNote: "5 Nov 2026",
		Eligibility: "≥3 entities/3 countries; civil-protection end users.", Note: "Flood/fire/mudslide decision support fits DRS topics; join a consortium (AIT, DLR, Fraunhofer often lead).",
		Score: 35, Why: "Consortium-only."},
	{Key: "ucpm", Name: "UCPM – Union Civil Protection Mechanism prevention & preparedness grants", URL: "https://civil-protection-humanitarian-aid.ec.europa.eu/funding-evaluations/financing-civil-protection/calls-for-proposal_en",
		Kind: "grant", Track: "eu", Amount: "2026 budget €15.1m; projects ~€0.5–1m", DeadlineNote: "2026 closed 19 May; next ~spring 2027 (verify)",
		Eligibility: "Consortia incl. civil-protection authorities; legal entity.", Note: "With BMI/Länder as partners.", Score: 35, Why: "2027; consortium."},
	{Key: "life-2026", Name: "EU LIFE 2026 – Climate Adaptation / Nature & Biodiversity", URL: "https://cinea.ec.europa.eu/programmes/life/life-calls-proposals-2026_en",
		Kind: "grant", Track: "eu", Amount: "60% of costs; projects €1–5m", DeadlineNote: "2026 topic deadlines ~Sep–Oct (verify portal)",
		Eligibility: "EU legal entities incl. SMEs; consortium not always mandatory.", Note: "LIFE funds implementation, not R&D — good for deploying the land-use tool with an Austrian authority.",
		Score: 40, Why: "Needs entity + authority partner."},
	{Key: "horizon-euspa-2027", Name: "Horizon Europe Cluster 4 Space – Copernicus downstream applications 2027", URL: "https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-details/HORIZON-EUSPA-2027-SPACE-02-51",
		Kind: "grant", Track: "space", Amount: "€3–5m per project", Deadline: "2027-03-02", DeadlineNote: "2 Mar 2027",
		Eligibility: "EU legal entities; consortium.", Note: "Exactly 'Copernicus-based applications for commercial uptake'. Time to build a consortium.",
		Score: 45, Why: "Perfect topic; 6 months to assemble."},
	{Key: "esa-bass-kickstart", Name: "ESA Business Applications – Kick-start Activities", URL: "https://business.esa.int/funding/invitation-to-tender",
		Kind: "grant", Track: "space", Amount: "up to €75k at 75% ESA funding", DeadlineNote: "thematic calls open continuously (verify current topic)",
		Eligibility: "Legal entity in ESA state; needs Austrian delegation (FFG/ALR) authorisation letter.", Note: "Smaller, faster sibling of InCubed – a 6-month feasibility study for the Austrian land-governance service.",
		Score: 60, Why: "Right size for a first EO contract; entity needed."},
	{Key: "ffg-innovationsscheck", Name: "FFG Innovationsscheck", URL: "https://www.ffg.at/innovationsscheck-mit-selbstbehalt",
		Kind: "grant", Track: "at", Amount: "€10k at 80%", DeadlineNote: "rolling",
		Eligibility: "Austrian SME (entity); buys work from a research institution.", Note: "Day-1-after-GmbH: pay TU Wien/BOKU to audit the LIDAR-watershed pipeline.",
		Score: 55, Why: "Small, easy, useful."},
	{Key: "ffg-ai-for-green", Name: "FFG AI for Green / AI Mission Austria", URL: "https://www.ffg.at/AI-for-Green",
		Kind: "grant", Track: "at", Amount: "cooperative R&D, call-specific", DeadlineNote: "no 2026 call open; watch (verify)",
		Eligibility: "Austrian entities/consortia.", Note: "AI on public geodata for climate = the call's purpose when it runs.", Score: 45, Why: "Topic fit; timing unknown."},
	{Key: "ams-ugp", Name: "AMS Unternehmensgründungsprogramm (UGP)", URL: "https://www.ams.at/arbeitsuchende/aus-und-weiterbildung/unternehmensgruendungsprogramm",
		Kind: "program", Track: "at", Amount: "subsistence continued + coaching during pre-founding (up to ~9 months)", DeadlineNote: "rolling",
		Eligibility: "Registered unemployed with AMS; viable idea. NB: mutually exclusive with the Gründungsstipendium.", Note: "Only relevant if you register with AMS between park jobs; then pick UGP *or* Gründungsstipendium, not both.",
		Score: 40, Why: "Situational."},

	// ---------- Individual-eligible prizes / fellowships ----------
	{Key: "rolex-awards", Name: "Rolex Awards for Enterprise", URL: "https://www.rolex.org/rolex-awards",
		Kind: "prize", Track: "prize", Amount: "CHF 200k per Laureate", DeadlineNote: "next cycle TBA (biennial-ish; verify)",
		Eligibility: "Individuals 18+, any nationality; original, active project led by applicant.", Note: "Individual-eligible, conservation-tech friendly; the CAR park monitoring story fits Rolex's profile.",
		Score: 55, Why: "Individual-eligible, big."},
	{Key: "echoing-green", Name: "Echoing Green Fellowship", URL: "https://echoinggreen.org/fellowship/",
		Kind: "prize", Track: "prize", Amount: "~$100k over 18 months + support", DeadlineNote: "annual (verify)",
		Eligibility: "Early-stage social-impact founders; full-time; primary decision-maker.", Note: "Pitch the free-for-poor-countries model.", Score: 45, Why: "Impact-model fit."},
	{Key: "drk-foundation", Name: "Draper Richards Kaplan Foundation", URL: "https://www.drkfoundation.org/apply-for-funding/",
		Kind: "grant", Track: "prize", Amount: "$300k unrestricted over 3 years + board seat", DeadlineNote: "rolling",
		Eligibility: "Early-stage nonprofit/hybrid/for-profit social enterprises, post-pilot.", Note: "After the CAR pilot is live.", Score: 45, Why: "Post-pilot."},
	{Key: "whitley", Name: "Whitley Awards 2027 (nominate a CAR partner)", URL: "https://whitleyaward.org/apply-for-conservation-funding/",
		Kind: "prize", Track: "conservation", Amount: "£50k", Deadline: "2026-10-31", DeadlineNote: "31 Oct 2026",
		Eligibility: "Global South nationals leading local conservation work – NOT you.", Note: "Nominate a Central African park leader who would use the app.", Score: 25, Why: "Not eligible yourself."},

	// ---------- CAR-side institutional money (partner, don't apply directly) ----------
	{Key: "cafi", Name: "CAFI – Central African Forest Initiative (CAR)", URL: "https://cafi.org/countries/central-african-republic",
		Kind: "grant", Track: "africa", Amount: "programme-scale (tens of $m via UN/implementers)", DeadlineNote: "via national investment framework; EOIs occasional",
		Eligibility: "Flows through government + accredited implementers (UNDP, FAO, WRI…).", Note: "Get Five Megapixel written into CAR's CAFI land-use-planning / forest-monitoring components as the national tool.",
		Score: 45, Why: "Big, indirect."},
	{Key: "legacy-landscapes", Name: "Legacy Landscapes Fund", URL: "https://legacylandscapes.org/funding/",
		Kind: "grant", Track: "africa", Amount: "$1m/yr per landscape, 15+ yrs", DeadlineNote: "periodic calls (verify)",
		Eligibility: "NGO + government partnerships for specific PAs.", Note: "Chinko/African Parks or WCS-managed sites in CAR; you as monitoring provider.", Score: 35, Why: "Partner role only."},
	{Key: "gef-sgp-car", Name: "GEF Small Grants Programme (UNDP CAR)", URL: "https://sgp.undp.org/",
		Kind: "grant", Track: "africa", Amount: "up to $50k (strategic $150k)", DeadlineNote: "country call-specific (verify with UNDP Bangui)",
		Eligibility: "Local registered CSOs.", Note: "Via your former NGO in CAR.", Score: 35, Why: "Local CSO vehicle."},
	{Key: "ci-ventures", Name: "Conservation International Ventures", URL: "https://www.conservation.org/projects/conservation-international-ventures",
		Kind: "vc", Track: "vc", Amount: "$0.5–2m flexible debt/equity", DeadlineNote: "rolling",
		Eligibility: "Revenue-generating conservation enterprises.", Note: "Later.", Score: 30, Why: "Post-revenue."},

	// ---------- Insurers (the other party paying for disaster risk) ----------
	{Key: "uniqa-ventures", Name: "UNIQA Ventures (Vienna)", URL: "https://www.uniqaventures.com/",
		Kind: "vc", Track: "vc", Amount: "seed–A, deal-specific", DeadlineNote: "rolling",
		Eligibility: "Incorporated; strategic value to insurance.", Note: "Flood/mudslide/fire exposure per parcel is underwriting gold. Also a potential first *customer* in Austria.",
		Score: 50, Why: "Local strategic; customer + investor."},
	{Key: "vig", Name: "Vienna Insurance Group – innovation / viesure", URL: "https://www.vig.com/en/innovation/",
		Kind: "vc", Track: "vc", Amount: "partnership/deal-specific", DeadlineNote: "rolling",
		Eligibility: "Incorporated.", Note: "Same pitch as UNIQA; CEE footprint matches 'Central European governments'.", Score: 45, Why: "Strategic partner."},
	{Key: "swissre-foundation", Name: "Swiss Re Foundation / Munich Re Foundation", URL: "https://www.swissrefoundation.org/",
		Kind: "grant", Track: "prize", Amount: "challenge-specific", DeadlineNote: "watch resilience challenges",
		Eligibility: "Usually established orgs.", Note: "", Score: 25, Why: "No open route."},

	// ---------- Cloud credits (need GmbH) ----------
	{Key: "gcp-startups", Name: "Google for Startups Cloud Program", URL: "https://cloud.google.com/startup",
		Kind: "program", Track: "program", Amount: "$2k–200k credits; up to $350k AI tier (needs backing)", DeadlineNote: "rolling",
		Eligibility: "Incorporated; larger tiers need investor/accelerator affiliation.", Note: "Earth Engine commercial runs on GCP – this is the natural home.", Score: 55, Why: "Earth Engine synergy."},
	{Key: "ms-founders-hub", Name: "Microsoft for Startups Founders Hub", URL: "https://www.microsoft.com/en-us/startups",
		Kind: "program", Track: "program", Amount: "up to $150k Azure by stage", DeadlineNote: "rolling",
		Eligibility: "Accepts pre-funding founders; verify unincorporated.", Note: "Planetary Computer lives here.", Score: 50, Why: "Possibly pre-entity."},

	// ---------- Discontinued / do not chase ----------
	{Key: "xprize-wildfire", Name: "XPRIZE Wildfire", URL: "https://www.xprize.org/competitions/wildfire", Kind: "prize", Track: "prize", Amount: "$11m purse", DeadlineNote: "closed – in finals 2026",
		Eligibility: "—", Note: "Watch XPRIZE for successor competitions.", Score: 0, Why: "Closed."},
	{Key: "copernicus-masters", Name: "Copernicus Masters", URL: "https://www.copernicus.eu/en/opportunities", Kind: "prize", Track: "space", Amount: "—", DeadlineNote: "discontinued (→ CASSINI)",
		Eligibility: "—", Note: "", Score: 0, Why: "Discontinued."},
	{Key: "myeuspace", Name: "EUSPA #myEUspace competition", URL: "https://www.euspa.europa.eu/myeuspacecompetition", Kind: "prize", Track: "space", Amount: "historically €1m pool", DeadlineNote: "no 2026 edition announced",
		Eligibility: "—", Note: "", Score: 0, Why: "Dormant."},
	{Key: "unccd-land-for-life", Name: "UNCCD Land for Life Award", URL: "https://www.unccd.int/our-work-impact/land-life-award", Kind: "prize", Track: "prize", Amount: "—", DeadlineNote: "not accepting nominations",
		Eligibility: "—", Note: "", Score: 0, Why: "Dormant."},
	{Key: "ms-ai-for-earth", Name: "Microsoft AI for Earth grants", URL: "https://www.microsoft.com/en-us/ai/ai-for-earth", Kind: "grant", Track: "program", Amount: "—", DeadlineNote: "no open global call",
		Eligibility: "—", Note: "", Score: 0, Why: "Closed."},
	{Key: "vienna-startup-package", Name: "Vienna Startup Package", URL: "https://wirtschaftsagentur.at/termine-events-workshops/vienna-startup-package-2026/", Kind: "accelerator", Track: "at", Amount: "travel ≤€3k", DeadlineNote: "for foreign startups only",
		Eligibility: "International founders relocating to Vienna.", Note: "", Score: 0, Why: "Not for locals."},
}
