// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package dbgen

import (
	"context"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (url, title, description, shelley_command, sort_order, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, url, title, description, shelley_command, sort_order, created_at, updated_at
`

type CreateAppParams struct {
	Url            string  `json:"url"`
	Title          string  `json:"title"`
	Description    string  `json:"description"`
	ShelleyCommand *string `json:"shelley_command"`
	SortOrder      *int64  `json:"sort_order"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRowContext(ctx, createApp,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.ShelleyCommand,
		arg.SortOrder,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.ShelleyCommand,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM apps WHERE id = ?
`

func (q *Queries) DeleteApp(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteApp, id)
	return err
}

const getApp = `-- name: GetApp :one
SELECT id, url, title, description, shelley_command, sort_order, created_at, updated_at FROM apps WHERE id = ?
`

func (q *Queries) GetApp(ctx context.Context, id int64) (App, error) {
	row := q.db.QueryRowContext(ctx, getApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.ShelleyCommand,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApps = `-- name: ListApps :many
SELECT id, url, title, description, shelley_command, sort_order, created_at, updated_at FROM apps ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.ShelleyCommand,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApp = `-- name: UpdateApp :exec
UPDATE apps SET
    url = ?,
    title = ?,
    description = ?,
    shelley_command = ?,
    sort_order = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateAppParams struct {
	Url            string  `json:"url"`
	Title          string  `json:"title"`
	Description    string  `json:"description"`
	ShelleyCommand *string `json:"shelley_command"`
	SortOrder      *int64  `json:"sort_order"`
	ID             int64   `json:"id"`
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) error {
	_, err := q.db.ExecContext(ctx, updateApp,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.ShelleyCommand,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
